### ISSUE TITLE
[feature request] Allow editing any empty line. Not only the top empty one.

### ISSUE THREAD

**Issue by cocoonkid** [Zuntek/WeekToDoWeb#115]
[feature request] Allow editing any empty line. Not ONLY the top empty one.

I often find myself wanting to create task but at the end of the list for later specification of time.

This would be immensely helpful.

**Comment by merodriguez9112** [comment]
@cocoonkid  thanks for the feedback. Initially when I made the first version I thought to implement it this way, but the lists are managed by indexes and if I enable this option I force users to have to go precisely to the first box to add a new task, or after they add it have to move to this position. 

This has several inconveniences since it supposes more steps to be carried out by the user, and it begins to generate empty events to maintain the positions when make the swap. I understand that it may be useful to you but given these inconveniences I think it is not a good idea to add it to the system.

 I hope it's not an inconvenience to you. :pray:

**Comment by cocoonkid** [comment]
Understood. Thanks for taking the time to explain.
