### ISSUE TITLE
Reorder option inside list's menu (three dots) doesn't work 

### ISSUE THREAD

**Issue by Ruler90** [Zuntek/WeekToDoWeb#144]
When I click on the three dots next to the list's name, there is a Reorder option. When I click it, nothing happens. This option can be found in calendar lists and custom lists.
![image](https://user-images.githubusercontent.com/54283970/178355061-f7260e04-7efc-4b8e-a094-d990bfbeb9f1.png)
![image](https://user-images.githubusercontent.com/54283970/178355005-3d1219ae-bb04-4a87-b1a6-076e6591b059.png)

Button on the left panel works as intended.
![image](https://user-images.githubusercontent.com/54283970/178355525-9ce60f63-19eb-491b-aabd-7a132d335b86.png)

Tested app v1.8.5:
- in Chrome
- installed Windows version

**Comment by merodriguez9112** [comment]
Hi @Ruler90 thanks for reporting this. Just to confirm. The behavior of the reorder action in the three dots is that what it should do is internally reorder the tasks: first by time, then the pending tasks,  and then the completed tasks. Here you can see the expected behavior

https://www.youtube.com/watch?v=fMr_yIAkyrI&ab_channel=WeekToDo

Is this what the app is not doing?

**Comment by merodriguez9112** [comment]
It's a good suggestion @Ruler90 thanks. :+1: I will work on that, right now the change log is not descriptive.

As the action works fine, I'm closing this issue
