### ISSUE TITLE
Export option scrambles text

### ISSUE THREAD

**Issue by GinjNTonic** [Zuntek/WeekToDoWeb#16]
Using the Snap version 1.4.0 I on Manjaro Plasma I get this bug where my file manager text scrambles when I try to export  
![weektodo export bug](https://user-images.githubusercontent.com/86722849/145369488-58df729b-98a5-466c-89ef-31f43eeb0682.png)

**Comment by merodriguez9112** [comment]
Wow this is super odd error mostly because it seems to be a problem in the OS UI. Can you tell me in what language do you have the app and what language does your operating system have?

**Comment by GinjNTonic** [comment]
I have the app set to English and my system is on British English.

**Comment by merodriguez9112** [comment]
Thanks @GinjNTonic I will try to replicate this error and try to find out what it's happening there :/

**Comment by merodriguez9112** [comment]
No matter how hard I try I can't replicate this problem, it has only happened this once, and I'm assuming it's an operating system problem or something for now I'm closing it in case it happens again I'll do a deeper search.

**Comment by Nels-J** [comment]
Hi @manuelernestog, 
actually I have the same issue since I try to export before reopening an issue may I miss something.

Using Ubuntu in english language, within the app if english or french language is used I have the same issue.

App version from Ubuntu app center (snap) latest/stable 2.1.0
May 2.2.0 version fix it but as you said in the previous comment you can't replicate it so you can't fix it I guess.

I had a look on issues open and closed and also on release notes but nothing ring me a bell on that way.

# System Details Report
- **Date generated:**                              2025-05-28 10:49:06
## Hardware Information:
- **Hardware Model:**                              Micro-Star International Co., Ltd. P75 Creator 9SD
- **Memory:**                                      32.0 GiB
- **Processor:**                                   Intel® Core™ i7-9750H × 12
- **Graphics:**                                    Intel® UHD Graphics 630 (CFL GT2)
- **Graphics 1:**                                  NVIDIA GeForce GTX 1660 Ti with Max-Q Design
## Software Information:
- **Firmware Version:**                            E17G1IMS.710
- **OS Name:**                                     Ubuntu 24.04.2 LTS
- **OS Type:**                                     64-bit
- **GNOME Version:**                               46
- **Windowing System:**                            X11
- **Kernel Version:**                              Linux 6.11.0-26-generic
--------------

Thanks for the amazing app ;-)
Kind regards.
Nelson.
