### ISSUE TITLE
Instructions on how to build

### ISSUE THREAD

**Issue by micjax** [Zuntek/WeekToDoWeb#63]
Hi, I want to build this app myself, can you publish the instructions (Linux is priority) 

 Thanks!

**Comment by fredguth** [comment]
It seems that only the website is in this repo.  When you click "Get Started" you go to app.weektodo.me and this is another code base AFAIK.

Am I wrong @merodriguez9112 ? Could you explain it in Readme a little bit more?
I hope to contribute with code.

**Comment by merodriguez9112** [comment]
Hi guys @fredguth @micjax Thanks for write :)

Sorry about the close and reopend, bad finger :/

Yes @fredguth you are rigth, this is the repo of the website.

Initially I started with the public app repo, but it never had contributions and I didn't like the only one that did, hahaha. To avoid that, a while ago I decided to close it and find a way to finance the project, I moved the builds to this repo and continue the development little by little on my own and see if I am able to keep it that way and when it reaches a point I want to see if with the sponsor model it manages to finance its development, otherwise I will have to see how I pivot and what I do with it. I hope this is not an inconvenience, if you have any suggestions or anything I am happy to hear it.

**Comment by micjax** [comment]
Hi!

Is the source code for binaries open? I couldn't find it when I was trying to build myself.

If not, I think that webiste is very misleading with privacy focus claims. Thanks in advance!

**Comment by merodriguez9112** [comment]
Hi @micjax I get the point, that's why it was initially open, but then because of what I explained above I closed it and moved the builds to this repository. I'll clarify that in the readme.

Regarding privacy in the web version, you can review the requests made by the app and realize that it only makes a request to render the list of contributors and sponsors and to check if there is a new version available.

**Comment by merodriguez9112** [comment]
> Hi guys @fredguth @micjax Thanks for write :)
> 
> Sorry about the close and reopend, bad finger :/
> 
> Yes @fredguth you are rigth, this is the repo of the website.
> 
> Initially I started with the public app repo, but it never had contributions and I didn't like the only one that did, hahaha. To avoid that, a while ago I decided to close it and find a way to finance the project, I moved the builds to this repo and continue the development little by little on my own and see if I am able to keep it that way and when it reaches a point I want to see if with the sponsor model it manages to finance its development, otherwise I will have to see how I pivot and what I do with it. I hope this is not an inconvenience, if you have any suggestions or anything I am happy to hear it.

Closing this issue
